### ISSUE TITLE
Source Maps are not working

### ISSUE THREAD

**Issue by fdietze** [outwatch/seed.g8#44]
This is probably a problem of `fun-pack`.

**Comment by cornerman** [comment]
We should really copy over a simplified template from `fun-stack/example`. That should fix it :)

**Comment by fdietze** [comment]
It's also broken in fun-stack Afaik.

**Comment by fdietze** [comment]
Also, it's already a simple copy of fun-stack.

**Comment by fdietze** [comment]
Actually they are working. False report from my side...
